name: tests
on:
  pull_request:
  push:
      branches: [main]
      paths: ['**.java']

jobs:
  run-tests:
    runs-on: ubuntu-latest
    if: "!contains(github.actor, 'weichbot10')"
    steps:
      - name: checkout the repository
        uses: actions/checkout@v2
      - name: setup java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'maven'
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml verify checkstyle:checkstyle
      - name: publish test report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
        with:
          fail_on_test_failures: false # change this to true once it matters
