name: update
permissions:
  actions: write
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Commit Message'
        required: true
        default: 'update from weichware10/repo-utils'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WEICHBOT }}
      - name: download workflows
        run: |
          curl https://raw.githubusercontent.com/weichware-10/repo-utils/main/workflows/badges.yaml --output .github/workflows/badges.yaml --create-dirs
          curl https://raw.githubusercontent.com/weichware-10/repo-utils/main/workflows/tests.yaml --output .github/workflows/tests.yaml --create-dirs
          curl https://raw.githubusercontent.com/weichware-10/repo-utils/main/workflows/update.yaml --output .github/workflows/update.yaml --create-dirs
          curl https://raw.githubusercontent.com/weichware-10/repo-utils/main/workflows/checkstyle.yaml --output .github/workflows/checkstyle.yaml --create-dirs
          curl https://raw.githubusercontent.com/weichware-10/repo-utils/main/workflows/tag.yaml --output .github/workflows/tag.yaml --create-dirs
          curl https://raw.githubusercontent.com/weichware-10/repo-utils/main/workflows/release.yaml --output .github/workflows/release.yaml --create-dirs
      - name: download checkstyle
        run: curl https://raw.githubusercontent.com/weichware-10/repo-utils/main/checkstyle.xml --output checkstyle.xml --create-dirs
      - name: download gitignore
        run: curl https://raw.githubusercontent.com/weichware-10/repo-utils/main/.gitignore --output .gitignore --create-dirs
      - name: import GPG
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.WEICHBOT_GPG_PRIVATE }}
          passphrase: ${{ secrets.WEICHBOT_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ github.event.inputs.message }}
          commit_user_name: 'weichbot10'
          commit_user_email: 'weichbot10@users.noreply.github.com'
